# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26
  gripper_joint_1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    # has_deceleration_limits: true
    # max_deceleration: -0.5
  gripper_joint_2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
    # has_deceleration_limits: true
    # max_deceleration: -0.5
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 0.26
    # has_deceleration_limits: true
    # max_deceleration: -0.26