# controller_manager provides the necessary infrastructure to manage multiple controllers efficiently and robustly using ROS 2 Control.
controller_manager:
  ros__parameters:
    update_rate: 10 # update_rate specifies how often (in Hz) the controllers should be updated.

    # The JointTrajectoryController allows you to send joint trajectory commands to a group 
    # of joints on a robot. These commands specify the desired positions for each joint.     
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    grip_controller:
      type: position_controllers/GripperActionController
    
    # Responsible for publishing the current state of the robot's joints to the /joint_states 
    # ROS 2 topic
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Define the parameters for each controller
arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # The controller will expect position commands as input for each of these joints.
    command_interfaces:
      - position
    
    # Tells the controller that it should expect to receive position data as the state 
    # feedback from the hardware interface,
    state_interfaces:
      - position

    # If true, When set to true, the controller will not use any feedback from the system 
    # (e.g., joint positions, velocities, efforts) to compute the control commands. 
   
    open_loop_control: false

    # When set to true, it allows the controller to integrate the trajectory goals it receives. 
    # This means that if the goal trajectory only specifies positions, the controller will 
    # numerically integrate the positions to compute the velocities and accelerations required 
    # to follow the trajectory.
    
    allow_integration_in_goal_trajectories: false

    constraints:
      stopped_velocity_tolerance: 0.001
      goal_time: 2.0
      shoulder_pan_joint:
        goal: 0.05
        trajectory: 0.0
      shoulder_lift_joint:
        goal: 0.05
        trajectory: 0.0
      elbow_joint:
        goal: 0.05
        trajectory: 0.0
      wrist_1_joint:
        goal: 0.05
        trajectory: 0.0
      wrist_2_joint:
        goal: 0.05
        trajectory: 0.0
      wrist_3_joint:
        goal: 0.05
        trajectory: 0.0
      

grip_controller:
  ros__parameters:
    joint: gripper_joint_1
    goal_tolerance: 0.001
    allow_stalling: true
    stall_timeout: 0.1
    stall_velocity_threshold: 0.1

